# Pipeline params
samplesheet: assets/samplesheet.de.example.csv
counts_matrix: assets/counts.example.tsv
de_counts_source: generated
condition_col: condition
control_level: control
treatment_level: treated
fdr_threshold: 0.05
fastp_threads: 2
fastp_extra: ""
reference_fasta: assets/reference.example.fa
star_index: null
star_index_threads: 4
star_index_overhang: 99
star_index_extra: ""
star_threads: 4
star_extra: ""
annotation_gtf: assets/genes.example.gtf
annotation_bed12: null
strandedness_inference_threshold: 0.8
strandedness_unstranded_tolerance: 0.1
featurecounts_threads: 2
featurecounts_extra: ""
outdir: results
container: file://./containers/yeast-rnaseq.sif
