# Pipeline params
samplesheet: assets/samplesheet.de.example.csv
counts_matrix: assets/counts.example.tsv
de_counts_source: auto
condition_col: condition
control_level: control
treatment_level: treated
fdr_threshold: 0.05
fastp_threads: 2
fastp_extra: ""
star_index: null
star_threads: 4
star_extra: ""
annotation_gtf: null
featurecounts_threads: 2
featurecounts_extra: ""
outdir: results
container: file://./containers/yeast-rnaseq.sif
